site_name: Python Twitter V2 Docs
site_description: Docs for python-twitetr-v2 library
repo_url: https://github.com/sns-sdks/python-twitter
copyright: Copyright &copy; 2021 - 2021 Ikaros kun

theme:
  name: material
  features:
    - navigation.tabs

palette:
  # Light mode
  - media: "(prefers-color-scheme: light)"
    scheme: default
    primary: indigo
    accent: indigo
    toggle:
      icon: material/toggle-switch-off-outline
      name: Switch to dark mode

  # Dark mode
  - media: "(prefers-color-scheme: dark)"
    scheme: slate
    primary: blue
    accent: blue
    toggle:
      icon: material/toggle-switch
      name: Switch to light mode

nav:
  - Introduction: index.md
  - Installation: installation.md
  - Authorization: authorization.md
  - Usage:
      - Preparation: usage/preparation.md
      - Users:
          - Users Lookup: usage/users/user-lookup.md
          - Follows: usage/users/follows.md
          - Blocks: usage/users/blocks.md
      - Tweets:
          - Tweet Lookup: usage/tweets/tweet-lookup.md
          - Timelines: usage/tweets/timelines.md
          - Search Tweets: usage/tweets/search_tweets.md
          - Tweet counts: usage/tweets/tweets_counts.md
          - Hide replies: usage/tweets/hide_reply.md
          - Likes: usage/tweets/likes.md
      - Steaming: usage/streaming.md
  - Changelog: CHANGELOG.md

extra:
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/realllkk520
    - icon: fontawesome/brands/github
      link: https://github.com/sns-sdks/python-youtube

markdown_extensions:
  - codehilite
  - admonition
  - pymdownx.superfences
  - pymdownx.emoji
