site_name: Python Twitter V2 Docs
site_description: Docs for python-twitetr-v2 library

theme:
  name: material
  features:
    - navigation.tabs

nav:
  - Introduction: index.md
  - Installation: installation.md
  - Authorization: authorization.md
  - Usage:
      - Preparation: usage/preparation.md
      - Users:
        - Users Lookup: usage/users/user-lookup.md
        - Follows: usage/users/follows.md

markdown_extensions:
  - codehilite
  - admonition
  - pymdownx.superfences
  - pymdownx.emoji
