site_name: Python Twitter V2 Docs
site_description: Docs for python-twitetr-v2 library

theme:
  name: material
  feature:
    tabs: true

nav:
  - Introduction: index.md
  - Installation: installation.md
  - Authorization: authorization.md
  - Basic Usage: basic-usage.md

markdown_extensions:
  - codehilite
  - admonition
  - pymdownx.superfences
  - pymdownx.emoji
