name: Publish Pypi
on:
  push:
    tags:
      - 'v*.*.*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build and publish to pypi
      uses: JRubics/poetry-publish@v2.1
      with:
        pypi_token: ${{ secrets.PYPI_TOKEN }}

    - name: Generate Changelog
      run: |
        VERSION=$(.github/hack/version.sh)
        .github/hack/changelog.sh $VERSION > NEW-VERSION-CHANGELOG.md

    - name: Publish
      uses: softprops/action-gh-release@v2
      with:
        body_path: NEW-VERSION-CHANGELOG.md
        files: 'python-twitter-*'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
